### ISSUE TITLE
No animation on updating data

### ISSUE THREAD

**Issue by AlexanderZubkov** [vlasov/CCBottomRefreshControl#10]
After releasing the tableView activity indicator should appear under the last cell. Sometimes it appears under the last one, sometimes it is inside the last cell and sometimes it may not appear at all. And when it does not appear you do not know if the tableView already updated or not.
I set userInteractionEnabled = NO when I start downloading new data and when I got it I call "end updating", [tableView reloadData] and userInteractionEnabled = YES all together. That is how I know when table is not updated yet but refresh control not appearing.

Do you know how to make it appear each time?

**Comment by vlasov** [comment]
Does Example project work fine for you?

**Comment by AlexanderZubkov** [comment]
Nikolay, thank you, it's working. It was wrong to set tableView.scrollEnabled = NO and tableView.userInteractionEnabled = NO inside (void)refreshBottom.
