### ISSUE TITLE
Component doesn't work in iOS 9

### ISSUE THREAD

**Issue by Ravul** [vlasov/CCBottomRefreshControl#16]
I've just installed XCode 7 and tested the project in iOS 9. It seems the component enters an infinite loop at the line 182 from UIScrollView+BottomRefreshControl.m: "[self brc_setContentOffset:contentOffset];" 
![screen shot 2015-09-20 at 8 12 47 pm](https://cloud.githubusercontent.com/assets/8264371/9981935/019295f2-5fd4-11e5-9bc9-b8c975cef0cd.png)

It is strange that I only use it for CollectionView and TableView but it appears as calling setContentOffset on UITextView.

**Comment by YK-Unit** [comment]
I got the same problem.It's so strange.

**Comment by razovVladimir** [comment]
Maybe u use UITextView+Placeholder or other projects which have method +(void) load { [super load]; //}

**Comment by Ravul** [comment]
Yes, that is exactly what am I using. Interesting. Do you have any ideas on how to fix it to be able to use both Categories?

**Comment by Ravul** [comment]
Ok, that was exactly the problem. I've fixed it. Thanks!
