### ISSUE TITLE
self.tableView.bottomRefreshControl = nil; throwing exception

### ISSUE THREAD

**Issue by marcelosalloum** [vlasov/CCBottomRefreshControl#4]
Hello Folks,

I am having trouble removing the bottomRefreshControl from my tableView. I am currently trying to do it by setting `self.tableView.bottomRefreshControl = nil;` but when I do so, I get a **EXC_BAD_ACCESS (code=2**.

How could I remove it once it is added?

Thanks,

**Comment by vlasov** [comment]
Possibly fixed. Try version 0.4.1
