### ISSUE TITLE
Stop Refreshing

### ISSUE THREAD

**Issue by golfguru1** [vlasov/CCBottomRefreshControl#5]
Is there a way to stop the refreshing animation once I have refreshed my collection view?

[refreshControl endRefreshing] doesn't do anything.

**Comment by maksimusenko** [comment]
I have the same thing

**Comment by ShreeshGarg** [comment]
Same thing with me, when I am trying to add refresh controller to the bottom of table .

**Comment by vlasov** [comment]
Have you called [refreshControl endRefreshing] immediately after [refreshControl beginRefreshing] ?

**Comment by ShreeshGarg** [comment]
No i am calling end refreshing after the completion of background thread.

**Comment by vlasov** [comment]
In this case did you wrap it, like:
        dispatch_async(dispatch_get_main_queue(), ^{
            [refreshControl endRefreshing];
        });
?

**Comment by ShreeshGarg** [comment]
I am doing same thing but with different approach. with performSelectorOnMailThread



Thanks
Shreesh Garg
750-3920-390

**Comment by vlasov** [comment]
Please try version 0.4.1
