### ISSUE TITLE
Error with iOS 7.1

### ISSUE THREAD

**Issue by vlad9486** [vlasov/CCBottomRefreshControl#6]
[!] The platform of the target `Pods` (iOS 7.1) is not compatible with `ReactiveCocoa (3.0.0-alpha.1)` which has a minimum requirement of iOS 8.0 - OS X 10.9.

I have commit that fixed this issue.
Change CCBottomRefreshControl.podspec as followed:
-  s.dependency 'ReactiveCocoa'
+  s.dependency 'ReactiveCocoa', '<= 2.0.0'

**Comment by vlasov** [comment]
Done

**Comment by xavierjurado** [comment]
This is not the recommended way of fixing this issue. Since `CCBottomRefreshControl` works with any version of RAC 2.x, you should use `>= 2.0` instead of `<= 2.0.0`. By using the latter, we have made `CCBottomRefreshControl` compatible only with RAC 2.0.0.

**Comment by vlasov** [comment]
RAC dependency has been removed since version 0.4.0
