### ISSUE TITLE
position of refresh control changes on orientation change 

### ISSUE THREAD

**Issue by AlexanderZubkov** [vlasov/CCBottomRefreshControl#8]
UITableView changes it's frame on orientation change but refresh control does not. I use auto layout. Any idea how to change control's position or make it follow tableview?

**Comment by AlexanderZubkov** [comment]
I even tried 
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration
{
    self.tableView.bottomRefreshControl = nil;
}

- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation
{
    UIRefreshControl *bottomRefreshControl = [UIRefreshControl new];
    [bottomRefreshControl addTarget:self action:@selector(refreshBottom) forControlEvents:UIControlEventValueChanged];
    
    self.tableView.bottomRefreshControl = bottomRefreshControl;
}

But with no luck...  Any idea?

**Comment by vlasov** [comment]
Thank you, Alex!

I’ve got a bug, and I’ll fix it soon. Maybe tomorrow.

Nick.

**Comment by AlexanderZubkov** [comment]
Thank you, Nick! Really waiting for it!

**Comment by vlasov** [comment]
Thank you for your patience.
I've deeply reworked whole implementation. Now it works way better and smoother. Autolayout bug was also fixed.
Please welcome version 0.4.1
